adn <- "AGCCTTT"
contar_nucleotidos <- function(adn) {
  n_A <- 0
  n_C <- 0
  n_G <- 0
  n_T <- 0
  for (nucleotido in strsplit(adn, "")[[1]]) {
    if (nucleotido == "A") {
      n_A <- n_A + 1
    } else if (nucleotido == "C") {
      n_C <- n_C + 1
    } else if (nucleotido == "G") {
      n_G <- n_G + 1
    } else if (nucleotido == "T") {
      n_T <- n_T + 1
    }
  }
  print(paste("Cantidad de A: ", n_A))
  print(paste("Cantidad de C: ", n_C))
  print(paste("Cantidad de G: ", n_G))
  print(paste("Cantidad de T: ", n_T))
  return(c(n_A, n_C, n_G, n_T))
}
contar_nucleotidos(adn)

adn <- "GATGGAACTTGACTACGTAAATT"
transcripcion <- function(adn) {
  arn <- ""
  for (nucleotido in strsplit(adn, "")[[1]]) {
    if (nucleotido == "A") {
      arn <- paste(arn, "A", sep = "")
    } else if (nucleotido == "C") {
      arn <- paste(arn, "C", sep = "")
    } else if (nucleotido == "G") {
      arn <- paste(arn, "G", sep = "")
    } else if (nucleotido == "T") {
      arn <- paste(arn, "U", sep = "")
    }
  }
  return(arn)
}
print(adn)
print(transcripcion(adn))

adn <- "AAAACCCGGT"
complementaria <- function(adn) {
  cc <- ""
  for (nucleotido in strsplit(adn, "")[[1]]) {
    if (nucleotido == "A") {
      cc <- paste(cc, "T", sep = "")
    } else if (nucleotido == "C") {
      cc <- paste(cc, "G", sep = "")
    } else if (nucleotido == "G") {
      cc <- paste(cc, "C", sep = "")
    } else if (nucleotido == "T") {
      cc <- paste(cc, "A", sep = "")
    }
  }
  return(cc)
}
print(adn)
print(complementaria(adn))

adn <- "AAAACCCGGT"
complementaria_inversa <- function(adn) {
  cci <- ""
  for (nucleotido in strsplit(adn, "")[[1]]) {
    if (nucleotido == "A") {
      cci <- paste("T", cci, sep = "")
    } else if (nucleotido == "C") {
      cci <- paste("G", cci, sep = "")
    } else if (nucleotido == "G") {
      cci <- paste("C", cci, sep = "")
    } else if (nucleotido == "T") {
      cci <- paste("A", cci, sep = "")
    }
  }
  return(cci)
}
print(adn)
print(complementaria_inversa(adn))

adn <- "ATGCCCAGAACTGAGATCAATAGTACCCGTATTAACGGGTGA"
arn <- transcripcion(adn)
aminoacidos <- list(
  "UUU" = "F", "UUC" = "F", "UUA" = "L", "UUG" = "L",
  "UCU" = "S", "UCC" = "s", "UCA" = "S", "UCG" = "S",
  "UAU" = "Y", "UAC" = "Y", "UAA" = "STOP", "UAG" = "STOP",
  "UGU" = "C", "UGC" = "C", "UGA" = "STOP", "UGG" = "W",
  "CUU" = "L", "CUC" = "L", "CUA" = "L", "CUG" = "L",
  "CCU" = "P", "CCC" = "P", "CCA" = "P", "CCG" = "P",
  "CAU" = "H", "CAC" = "H", "CAA" = "Q", "CAG" = "Q",
  "CGU" = "R", "CGC" = "R", "CGA" = "R", "CGG" = "R",
  "AUU" = "I", "AUC" = "I", "AUA" = "I", "AUG" = "M",
  "ACU" = "T", "ACC" = "T", "ACA" = "T", "ACG" = "T",
  "AAU" = "N", "AAC" = "N", "AAA" = "K", "AAG" = "K",
  "AGU" = "S", "AGC" = "S", "AGA" = "R", "AGG" = "R",
  "GUU" = "V", "GUC" = "V", "GUA" = "V", "GUG" = "V",
  "GCU" = "A", "GCC" = "A", "GCA" = "A", "GCG" = "A",
  "GAU" = "D", "GAC" = "D", "GAA" = "E", "GAG" = "E",
  "GGU" = "G", "GGC" = "G", "GGA" = "G", "GGG" = "G"
)
arn
traduccion <- function(arn) {
  proteina <- ""
  for (i in seq(1, nchar(arn), 3)) {
    codon <- substr(arn, i, i + 2)
    aminoacido <- aminoacidos[[codon]]
    if (aminoacido == "STOP") {
      break
    } else {
      proteina <- paste(proteina, aminoacido, sep = "")
    }
  }
  return(proteina)
}
print(traduccion(arn))

adn <- "ATGGGCATTCTGCCGAGCCCGGGCATGCCGGCGCTGCTGAGCCTGGTGAGCCTGCTGAGC \
        GTGCTGCTGATGGGCTGCGTGGCGGAAACCGGCACCCAGTGCGTGAACCTGACCACCCGC \
        ACCCAGCTGCCGCCGGCGTATACCAACAGCTTTACCCGCGGCGTGTATTATCCGGATAAA \
        GTGTTTCGCAGCAGCGTGCTGCATAGCACCCAGGATCTGTTTCTGCCGTTTTTTAGCAAC \
        GTGACCTGGTTTCATGCGATTCATGTGAGCGGCACCAACGGCACCAAACGCTTTGATAAC \
        CCGGTGCTGCCGTTTAACGATGGCGTGTATTTTGCGAGCACCGAAAAAAGCAACATTATT \
        CGCGGCTGGATTTTTGGCACCACCCTGGATAGCAAAACCCAGAGCCTGCTGATTGTGAAC \
        AACGCGACCAACGTGGTGATTAAAGTGTGCGAATTTCAGTTTTGCAACGATCCGTTTCTG \
        GGCGTGTATTATCATAAAAACAACAAAAGCTGGATGGAAAGCGAATTTCGCGTGTATAGC \
        AGCGCGAACAACTGCACCTTTGAATATGTGAGCCAGCCGTTTCTGATGGATCTGGAAGGC \
        AAACAGGGCAACTTTAAAAACCTGCGCGAATTTGTGTTTAAAAACATTGATGGCTATTTT \
        AAAATTTATAGCAAACATACCCCGATTAACCTGGTGCGCGATCTGCCGCAGGGCTTTAGC \
        GCGCTGGAACCGCTGGTGGATCTGCCGATTGGCATTAACATTACCCGCTTTCAGACCCTG \
        CTGGCGCTGCATCGCAGCTATCTGACCCCGGGCGATAGCAGCAGCGGCTGGACCGCGGGC \
        GCGGCGGCGTATTATGTGGGCTATCTGCAGCCGCGCACCTTTCTGCTGAAATATAACGAA \
        AACGGCACCATTACCGATGCGGTGGATTGCGCGCTGGATCCGCTGAGCGAAACCAAATGC \
        ACCCTGAAAAGCTTTACCGTGGAAAAAGGCATTTATCAGACCAGCAACTTTCGCGTGCAG \
        CCGACCGAAAGCATTGTGCGCTTTCCGAACATTACCAACCTGTGCCCGTTTGGCGAAGTG \
        TTTAACGCGACCCGCTTTGCGAGCGTGTATGCGTGGAACCGCAAACGCATTAGCAACTGC \
        GTGGCGGATTATAGCGTGCTGTATAACAGCGCGAGCTTTAGCACCTTTAAATGCTATGGC \
        GTGAGCCCGACCAAACTGAACGATCTGTGCTTTACCAACGTGTATGCGGATAGCTTTGTG \
        ATTCGCGGCGATGAAGTGCGCCAGATTGCGCCGGGCCAGACCGGCAAAATTGCGGATTAT \
        AACTATAAACTGCCGGATGATTTTACCGGCTGCGTGATTGCGTGGAACAGCAACAACCTG \
        GATAGCAAAGTGGGCGGCAACTATAACTATCTGTATCGCCTGTTTCGCAAAAGCAACCTG \
        AAACCGTTTGAACGCGATATTAGCACCGAAATTTATCAGGCGGGCAGCACCCCGTGCAAC \
        GGCGTGGAAGGCTTTAACTGCTATTTTCCGCTGCAGAGCTATGGCTTTCAGCCGACCAAC \
        GGCGTGGGCTATCAGCCGTATCGCGTGGTGGTGCTGAGCTTTGAACTGCTGCATGCGCCG \
        GCGACCGTGTGCGGCCCGAAAAAAAGCACCAACCTGGTGAAAAACAAATGCGTGAACTTT \
        AACTTTAACGGCCTGACCGGCACCGGCGTGCTGACCGAAAGCAACAAAAAATTTCTGCCG \
        TTTCAGCAGTTTGGCCGCGATATTGCGGATACCACCGATGCGGTGCGCGATCCGCAGACC \
        CTGGAAATTCTGGATATTACCCCGTGCAGCTTTGGCGGCGTGAGCGTGATTACCCCGGGC \
        ACCAACACCAGCAACCAGGTGGCGGTGCTGTATCAGGATGTGAACTGCACCGAAGTGCCG \
        GTGGCGATTCATGCGGATCAGCTGACCCCGACCTGGCGCGTGTATAGCACCGGCAGCAAC \
        GTGTTTCAGACCCGCGCGGGCTGCCTGATTGGCGCGGAACATGTGAACAACAGCTATGAA \
        TGCGATATTCCGATTGGCGCGGGCATTTGCGCGAGCTATCAGACCCAGACCAACAGCCCG \
        AGCGGCGCGGGCAGCGTGGCGAGCCAGAGCATTATTGCGTATACCATGAGCCTGGGCGCG \
        GAAAACAGCGTGGCGTATAGCAACAACAGCATTGCGATTCCGACCAACTTTACCATTAGC \
        GTGACCACCGAAATTCTGCCGGTGAGCATGACCAAAACCAGCGTGGATTGCACCATGTAT \
        ATTTGCGGCGATAGCACCGAATGCAGCAACCTGCTGCTGCAGTATGGCAGCTTTTGCACC \
        CAGCTGAACCGCGCGCTGACCGGCATTGCGGTGGAACAGGATAAAAACACCCAGGAAGTG \
        TTTGCGCAGGTGAAACAGATTTATAAAACCCCGCCGATTAAAGATTTTGGCGGCTTTAAC \
        TTTAGCCAGATTCTGCCGGATCCGAGCAAACCGAGCAAACGCAGCTTTATTGAAGATCTG \
        CTGTTTAACAAAGTGACCCTGGCGGATGCGGGCTTTATTAAACAGTATGGCGATTGCCTG \
        GGCGATATTGCGGCGCGCGATCTGATTTGCGCGCAGAAATTTAACGGCCTGACCGTGCTG \
        CCGCCGCTGCTGACCGATGAAATGATTGCGCAGTATACCAGCGCGCTGCTGGCGGGCACC \
        ATTACCAGCGGCTGGACCTTTGGCGCGGGCGCGGCGCTGCAGATTCCGTTTGCGATGCAG \
        ATGGCGTATCGCTTTAACGGCATTGGCGTGACCCAGAACGTGCTGTATGAAAACCAGAAA \
        CTGATTGCGAACCAGTTTAACAGCGCGATTGGCAAAATTCAGGATAGCCTGAGCAGCACC \
        GCGAGCGCGCTGGGCAAACTGCAGGATGTGGTGAACCAGAACGCGCAGGCGCTGAACACC \
        CTGGTGAAACAGCTGAGCAGCAACTTTGGCGCGATTAGCAGCGTGCTGAACGATATTCTG \
        AGCCGCCTGGATCCGCCGGAAGCGGAAGTGCAGATTGATCGCCTGATTACCGGCCGCCTG \
        CAGAGCCTGCAGACCTATGTGACCCAGCAGCTGATTCGCGCGGCGGAAATTCGCGCGAGC \
        GCGAACCTGGCGGCGACCAAAATGAGCGAATGCGTGCTGGGCCAGAGCAAACGCGTGGAT \
        TTTTGCGGCAAAGGCTATCATCTGATGAGCTTTCCGCAGAGCGCGCCGCATGGCGTGGTG \
        TTTCTGCATGTGACCTATGTGCCGGCGCAGGAAAAAAACTTTACCACCGCGCCGGCGATT \
        TGCCATGATGGCAAAGCGCATTTTCCGCGCGAAGGCGTGTTTGTGAGCAACGGCACCCAT \
        TGGTTTGTGACCCAGCGCAACTTTTATGAACCGCAGATTATTACCACCGATAACACCTTT \
        GTGAGCGGCAACTGCGATGTGGTGATTGGCATTGTGAACAACACCGTGTATGATCCGCTG \
        CAGCCGGAACTGGATAGCTTTAAAGAAGAACTGGATAAATATTTTAAAAACCATACCAGC \
        CCGGATGTGGATCTGGGCGATATTAGCGGCATTAACGCGAGCGTGGTGAACATTCAGAAA \
        GAAATTGATCGCCTGAACGAAGTGGCGAAAAACCTGAACGAAAGCCTGATTGATCTGCAG \
        GAACTGGGCAAATATGAACAGTATATTAAAGGCAGCGGCCGCGAAAACCTGTATTTTCAG \
        GGCGGCGGCGGCAGCGGCTATATTCCGGAAGCGCCGCGCGATGGCCAGGCGTATGTGCGC \
        AAAGATGGCGAATGGGTGCTGCTGAGCACCTTTCTGGGCCATCATCATCATCATCATCAT \
        CAT"
arn <- transcripcion(adn)
print(arn)
proteina <- traduccion(arn)
print(proteina)

install.packages("bio3d")
library(bio3d)
download.file("https://files.rcsb.org/download/6VXX.pdb", "protein.pdb")
structure <- read.pdb("protein.pdb")

# Modify from here to plot protein
# 
# view <- read.pdb("protein.pdb")
# view


